### ISSUE TITLE
Null token error on my android tv box

### ISSUE THREAD

**Issue by PyT** [rogro82/PiPup#17]
Hi,

I'm facing a null token error on my android tv based box (a mini 4k Freebox from a French provider).
Any idea what could be the reason ? See logs below. 
(I set SYSTEM_ALERT_WINDOW to allow of course)

`04-05 19:43:02.531  5187 15408 D PiPupService: received popup: PopupProps(duration=30, position=TopRight, backgroundColor=#ffffff, title=Your awesome title, titleSize=20.0, titleColor=#0066cc, message=What ever you want to say... do it here..., messageSize=14.0, messageColor=#000000, media=null)
04-05 19:43:02.531  5187  5187 D PiPupService: Create popup: PopupProps(duration=30, position=TopRight, backgroundColor=#ffffff, title=Your awesome title, titleSize=20.0, titleColor=#0066cc, message=What ever you want to say... do it here..., messageSize=14.0, messageColor=#000000, media=null)

04-05 19:43:02.538  2947 21055 W WindowManager: Attempted to add a toast window with bad token null.  Aborting.

04-05 19:43:02.539  5187  5187 W System.err: android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
04-05 19:43:02.544  5187  5187 W System.err: 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
04-05 19:43:02.544  5187  5187 W System.err: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
04-05 19:43:02.544  5187  5187 W System.err: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
04-05 19:43:02.544  5187  5187 W System.err: 	at nl.rogro82.pipup.PiPupService.createPopup(PiPupService.kt:136)
04-05 19:43:02.544  5187  5187 W System.err: 	at nl.rogro82.pipup.PiPupService.access$createPopup(PiPupService.kt:23)
04-05 19:43:02.544  5187  5187 W System.err: 	at nl.rogro82.pipup.PiPupService$handleHttpRequest$$inlined$let$lambda$2.run(PiPupService.kt:265)
04-05 19:43:02.544  5187  5187 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
04-05 19:43:02.544  5187  5187 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-05 19:43:02.544  5187  5187 W System.err: 	at android.os.Looper.loop(Looper.java:154)
04-05 19:43:02.544  5187  5187 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
04-05 19:43:02.544  5187  5187 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
04-05 19:43:02.544  5187  5187 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-05 19:43:02.544  5187  5187 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-05 19:43:33.384 14008 14036 D PICASSOGET: getting image http://127.0.0.1:1347/epg_imgs_url/programs/362x280/COL_422794_AG.jpg
04-05 19:43:33.396 14008 15411 D PICASSOGET: getting image content://android.media.tv/channel/208/logo
04-05 19:43:33.400 14008 15411 W System.err: java.io.FileNotFoundException: content://android.media.tv/channel/208/logo
04-05 19:43:33.401 14008 15411 W System.err: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:144)
04-05 19:43:33.401 14008 15411 W System.err: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
04-05 19:43:33.401 14008 15411 W System.err: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1147)
04-05 19:43:33.401 14008 15411 W System.err: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:984)
04-05 19:43:33.402 14008 15411 W System.err: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:704)
04-05 19:43:33.402 14008 15411 W System.err: 	at com.squareup.picasso.ContentStreamRequestHandler.getInputStream(ContentStreamRequestHandler.java:44)
04-05 19:43:33.402 14008 15411 W System.err: 	at com.squareup.picasso.ContentStreamRequestHandler.load(ContentStreamRequestHandler.java:39)
04-05 19:43:33.402 14008 15411 W System.err: 	at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
04-05 19:43:33.402 14008 15411 W System.err: 	at com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)
04-05 19:43:33.402 14008 15411 W System.err: 	at com.android.tv.util.BitmapUtils.decodeSampledBitmapFromUriString(BitmapUtils.java:75)
04-05 19:43:33.402 14008 15411 W System.err: 	at com.android.tv.util.ImageLoader$LoadBitmapFromUriTask.doGetBitmapInBackground(ImageLoader.java:369)
04-05 19:43:33.402 14008 15411 W System.err: 	at com.android.tv.util.ImageLoader$LoadBitmapTask.doInBackground(ImageLoader.java:332)
04-05 19:43:33.402 14008 15411 W System.err: 	at com.android.tv.util.ImageLoader$LoadBitmapTask.doInBackground(ImageLoader.java:327)
04-05 19:43:33.402 14008 15411 W System.err: 	at android.os.AsyncTask$2.call(AsyncTask.java:305)
04-05 19:43:33.402 14008 15411 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-05 19:43:33.402 14008 15411 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-05 19:43:33.402 14008 15411 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-05 19:43:33.402 14008 15411 W System.err: 	at java.lang.Thread.run(Thread.java:761)
04-05 19:43:33.416  1763  1773 I art     : CollectorTransition marksweep + semispace GC freed 419(26KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 2MB/3MB, paused 10.072ms total 10.072ms
04-05 19:43:33.432  2947  2947 V NotificationService: pkg=fr.freebox.tv canInterrupt=false intercept=true
04-05 19:43:33.539  3486  3486 D B-RecommendationsManager: ClientHandler#handleMessage: msg={ when=0 what=1 target=com.google.android.tvrecommendations.service.RecommendationsManager$ClientHandler }
04-05 19:43:33.539  3486  3486 D B-RecommendationsManager: 	msg.what=MSG_NOTIFICATION (1)
04-05 19:43:33.540  3486  3486 D B-RecommendationsManager: recommendationBatchPostedInt:
04-05 19:43:33.540  3486  3486 D B-RecommendationsManager: 	postedBatch=[RecOperation(ADD): StatusBarNotification(pkg=fr.freebox.tv user=UserHandle{0} id=0 tag=tv_recommendation key=0|fr.freebox.tv|0|tv_recommendation|10012: Notification(pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0xff0288d1 category=recommendation sortKey=1 vis=PRIVATE))]
04-05 19:43:33.540  3486  3486 D B-RecommendationsManager: 	mStarted=true
04-05 19:43:33.541  3486  3486 D Ranker  : markPostedRecommendations: packageName=fr.freebox.tv
04-05 19:43:33.541  3486  3486 D Ranker  : isBlacklisted: packageName="fr.freebox.tv" -> false
04-05 19:43:33.541  3486  3486 D B-RecommendationsManager: postRecommendationChangesToClients`

**Comment by sangood** [comment]
/app/src/main/java/nl/rogro82/pipup/PiPupService.kt

val layoutFlags: Int = when {
    Build.VERSION.SDK_INT >= Build.VERSION_CODES.O -> WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
    else -> WindowManager.LayoutParams.TYPE_SYSTEM_ALERT //modify here
}

**Comment by buptsb** [comment]
> /app/src/main/java/nl/rogro82/pipup/PiPupService.kt
> 
> val layoutFlags: Int = when { Build.VERSION.SDK_INT >= Build.VERSION_CODES.O -> WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY else -> WindowManager.LayoutParams.TYPE_SYSTEM_ALERT //modify here }

Work like a charm on 7.1.2!
